### ISSUE TITLE
Crash on NurApiBLEAutoConnect

### ISSUE THREAD

**Issue by rcarondecathlon** [NordicID/nur_sample_android#10]
Hi, 

We faced an issue that we were able to reproduce only one time. Connection on EXA31 device works, but one time we had this error :
`Fatal Exception: java.lang.OutOfMemoryError: Could not allocate JNI Env
       at java.lang.Thread.nativeCreate(Thread.java)
       at java.lang.Thread.start(Thread.java:730)
       at com.nordicid.nurapi.NurApiBLEAutoConnect$3.run(NurApiBLEAutoConnect.java:198)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6123)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)`

Our process to connect on Exa31 : 
`BleScanner.init(context)
            mBLEAuto = NurApiBLEAutoConnect(context, nurApi)
            mBLEAuto?.address = macAddress`

Thanks

**Comment by ekkilm** [comment]
Hi,

Thanks for the report.

Unfortunately, I was not able to reproduce the issue on my side. The connection on the EXA31 device appears to be working as expected.

From the description, it seems that you might be referring to Smart Pairing functionality?

In any case, we’ll keep an eye on this, and feel free to reach out if the problem occurs again or becomes more consistent — then we’ll investigate further.
